version: '3.3'

services:
  database:
    image: postgres
    container_name: cycleus-container
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
