version: '3.8'

services:
  database:
    image: 'postgres'
    env_file:
      - db.env
    volumes:
      - ./data:/var/lib/postgresql/database
    ports:
      - '8000:80'
    enviroment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database

volumes:
  pgdata:
    driver: local
    